### PR TITLE
Add runner parameters

### PR DESCRIPTION
**Pull request by rchicoli**
hey @Jeoffreybauvin, I've got some free time today for improving a bit the define runner function.

Please let me know what you do think about the changes

### CODE REVIEW

**Comment by rchicoli** [comment]
I've just found a duplicate entry. Give me some minute, I will pull the changes to this PR.

**Comment by rchicoli** [comment]
Ok now I fixed it and also rebase the branch.
Give a look and tell me if you like the changes, I would appreciate.

**Comment by Jeoffreybauvin** [comment]
Hi :)

A little question : why moving the create_resources in init.pp ?

**Comment by rchicoli** [comment]
Hi @Jeoffreybauvin, as far as I understand the variable `$runners` returns a hash of the class `gitlab_gitlab_ci_multi_runner`.

So it is easier to bind the resource to the main class instead of using `gitlab_ci_multi_runner::config::runners`

``` puppet
create_resources(gitlab_ci_multi_runner::runner, $runners)
```

that is exactly how the puppetlabs-apt module is built:
https://github.com/puppetlabs/puppetlabs-apt/blob/master/manifests/init.pp

I just think that it makes easier for anyone to catch up where the resource has been created. But if you don't like the change I can revert that.

What do you think?

**Comment by Jeoffreybauvin** [comment]
No it's good for me ;). Thanks !

**Pull request merged**
